### ISSUE TITLE
mode-line显示为一条红条

### ISSUE THREAD

**Issue by LambdaRan** [manateelazycat/lazycat-theme#1]
您好，使用新的主题代码，按说会禁用mode-line，使用awesome-tray代替，但是我这里mode-line会出现一条红条。我发现把 (mode-line-buffer-id :weight 'bold  :height 0.1) 这行代码屏蔽掉不会出现上面的问题，不知是因为啥引起的？

<img width="1100" alt="theme" src="https://user-images.githubusercontent.com/24838086/77256158-66e76380-6ca7-11ea-8569-c368a2bc5590.png">

**Comment by manateelazycat** [comment]
你要安装 awesome-tray.
